/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as TakenRouteImport } from './app/routes/taken'
import { Route as ProfileRouteImport } from './app/routes/profile'
import { Route as MyTasksRouteImport } from './app/routes/my-tasks'
import { Route as MarketplaceRouteImport } from './app/routes/marketplace'
import { Route as ChatRouteImport } from './app/routes/chat'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as authRegisterRouteImport } from './app/routes/(auth)/register'
import { Route as authLoginRouteImport } from './app/routes/(auth)/login'
import { Route as appDashboardRouteImport } from './app/routes/(app)/dashboard'

const TakenRoute = TakenRouteImport.update({
  id: '/taken',
  path: '/taken',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-tasks': typeof MyTasksRoute
  '/profile': typeof ProfileRoute
  '/taken': typeof TakenRoute
  '/dashboard': typeof appDashboardRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-tasks': typeof MyTasksRoute
  '/profile': typeof ProfileRoute
  '/taken': typeof TakenRoute
  '/dashboard': typeof appDashboardRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-tasks': typeof MyTasksRoute
  '/profile': typeof ProfileRoute
  '/taken': typeof TakenRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/marketplace'
    | '/my-tasks'
    | '/profile'
    | '/taken'
    | '/dashboard'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/marketplace'
    | '/my-tasks'
    | '/profile'
    | '/taken'
    | '/dashboard'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/marketplace'
    | '/my-tasks'
    | '/profile'
    | '/taken'
    | '/(app)/dashboard'
    | '/(auth)/login'
    | '/(auth)/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyTasksRoute: typeof MyTasksRoute
  ProfileRoute: typeof ProfileRoute
  TakenRoute: typeof TakenRoute
  appDashboardRoute: typeof appDashboardRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taken': {
      id: '/taken'
      path: '/taken'
      fullPath: '/taken'
      preLoaderRoute: typeof TakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyTasksRoute: MyTasksRoute,
  ProfileRoute: ProfileRoute,
  TakenRoute: TakenRoute,
  appDashboardRoute: appDashboardRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
